### PR TITLE
Update the compiled wasm-compiler module to gleam/main

### PR DESCRIPTION
**Pull request by JohnDoneth**
Trying to keep up with my fork of the compiler which was just caught up with gleam/main.

### CODE REVIEW

**Comment by inoas** [comment]
Issue `Uncaught (in promise) TypeError: undefined has no properties` when hitting `[Build]` with target Erlang (target Javascript works just fine)

Test Plattform Mac Firefox 95.0.2

**Comment by inoas** [comment]
Same issue in Mac Chrome Version 96.0.4664.110 (Official Build) (x86_64):

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'create')
    at At (app.bundle.js:2)
    at e.setValue (app.bundle.js:2)
    at Nn.setValue (app.bundle.js:2)
    at compile (app.bundle.js:2)
At @ app.bundle.js:2
setValue @ app.bundle.js:2
setValue @ app.bundle.js:2
compile @ app.bundle.js:2
await in compile (async)
(anonymous) @ app.bundle.js:2
```

**Comment by JohnDoneth** [comment]
@inoas Thanks for the report! Should be good now! Was a bad path on the JavaScript side when looking up the Erlang file. Eventually I'll add some tests to catch these things.

**Comment by inoas** [comment]
@JohnDoneth works for me, now onMac Firefox, Mac Safari, Mac Chrome, iOS Safari.

**Pull request merged**
