### PR TITLE
Add support for bitstrings in logger

### PR DESCRIPTION
**Pull request by Aloso**
The bytes can be displayed either as hexadecimal numbers or as UTF-8 string. There's a button to switch between the two.

Try it with

```rs
pub fn main() {
  <<"hello world":utf8>>
}
```

### CODE REVIEW

**Review by JohnDoneth — COMMENTED** [review]
This is neat! Should `io.debug` support the "to string" toggle? It appears that only the return value from `main()` works for the toggle.

[Playground Link](https://deploy-preview-15--gleam-playground.netlify.app/?s=JYWwDg9gTgLgBAcwDYFMCGID0wIChdgCuARnAGYB2cIawFAFAJRwDeuccOAdACYrGEE9ADzCARAAsUSJBDgB3aEh5iAXIRhkAHAD4djdnFGTpshUpXrNunbgC%2BQA)

**Comment by JohnDoneth** [comment]
> This is neat! Should `io.debug` support the "to string" toggle?

Maybe not since that appears to call `inspect` on the value first before calling `console.log`.

**Comment by Aloso** [comment]
@JohnDoneth yes. `io.debug` prints a string, so there's nothing I can do to format this, short of trying to parse every string printed to the console.

If you want to debug any value, you can use

```rs
external fn log(a) -> Nil = "" "console.log"
```

**Comment by JohnDoneth** [comment]
Gotcha! Thanks for this! ♥️

**Pull request merged**
